### ISSUE TITLE
Add support for RedHat platforms

### ISSUE THREAD

**Issue by bbaassssiiee** [nodesource/ansible-nodejs-role#22]
Ubuntu is nice but my employer runs RHEL.

**Comment by geerlingguy** [comment]
@bbaassssiiee - Check out https://github.com/geerlingguy/ansible-role-nodejs for now.

**Comment by bbaassssiiee** [comment]
@geerlingguy, will you really accept the long-term maintenance burden for ansible roles for every piece of software? You made quite a few, and are famous for it, but I think in this case @nodesource should maintain the Nodejs role and add RedHat support, similar to @elastic being responsible for 'the' Elasticsearch role.

**Comment by geerlingguy** [comment]
@bbaassssiiee 

> will you really accept the long-term maintenance burden for ansible roles for every piece of software?

Definitely not, but for any role I maintain, I'll at least make sure tests pass, it runs on all the OSes I use, etc.—almost all the roles I have on GitHub are roles that production servers under my care run on, so I have vested interest in making them work. At least minimally :)

> in this case @nodesource should maintain the Nodejs role and add RedHat support, similar to @elastic being responsible for 'the' Elasticsearch role.

No doubt. However, asking a team whose primary role is to build an application or something along those lines to also maintain the official roles/plugins/modules for all config management and packaging systems is a very difficult task—even if said developers work for a unicorn company with tons of VC backing!

There's always room for many roles, and different maintainers have different approaches. I support a base of features (not necessarily all), test all PRs and commits on almost all supported OSes, and support CentOS and Ubuntu at a minimum.

It seems that Nodesource supports only Ubuntu at this time (at least for the Ansible role), and for users who need multi-platform support—until and unless Nodesource chooses to support RHEL/CentOS/Fedora—they need to look elsewhere or fork and maintain their own role (both viable options).

**Comment by bbaassssiiee** [comment]
Fork and PR is a bit better, once accepted the maintenance lies with the guys making the money

**Comment by bbaassssiiee** [comment]
5 years of neglect noted.
