### ISSUE TITLE
Can't install the specific version of nodejs

### ISSUE THREAD

**Issue by arbabnazar** [nodesource/ansible-nodejs-role#32]
TASK [ansible-nodejs-role : Install Node.js] ***********************************
fatal: [192.168.33.33]: FAILED! => {"cache_update_time": 1472710763, "cache_updated": true, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'nodejs=4.4*'' failed: E: Version '4.4*' for 'nodejs' was not found\n", "stderr": "E: Version '4.4*' for 'nodejs' was not found\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information..."]}

**Comment by wolfeidau** [comment]
Gday have a read over #24 for the state of this issue, best to watch that issue for a fix.
