### ISSUE TITLE
bionic (ubuntu 18.04), gpg required

### ISSUE THREAD

**Issue by srl295** [nodesource/ansible-nodejs-role#43]
*Import the NodeSource GPG key into apt* fails with
> `Failed to find required executable gpg`

should this role install gpg as a prerequisite?

**Comment by chrislea** [comment]
Yeah, it should. This ansible role is pretty unmaintained atm, but this should be closed by https://github.com/nodesource/ansible-nodejs-role/commit/cbbbfe10fa71ca3f5cc7a98e549c2a4e06fc2f3b.
